apiVersion: v1
kind: Service
metadata:
  labels:
    app: incerment
  name: incerment
  namespace: my-ns
spec:
  type: ClusterIP
  ports:
  - name: "incerment-service"
    port: 3000
    targetPort: 3000
  selector:
    app: incerment