apiVersion: v1
kind: Service
metadata:
  labels:
    app: results
  name: results
  namespace: my-ns
spec:
  type: NodePort
  ports:
  - name: "results-service"
    port: 4000
    targetPort: 4000
    nodePort: 31000
  selector:
    app: results